### ISSUE TITLE
CTD due to FogTweaker / attached log

### ISSUE THREAD

**Issue by mysterious-static** [Warhand/Limitless_rebirth#1]
**Describe the bug**
Crashes when joining world

**To Reproduce**
1. Launch client
2. Join singleplayer or multiplayer world
3. CTD immediately on world join

**Expected behavior**
Joins into world successfully

**Modpack version:**
- Public Beta 3
- 
**Desktop (please complete the following information):**
 - Win10 x64 / Java 17
 - 
**Additional context**
Removing FogTweaker fixes the issue!

[crash-2022-04-27_12.08.45-client.txt](https://github.com/Warhand/Limitless_rebirth/files/8577514/crash-2022-04-27_12.08.45-client.txt)

**Comment by Warhand** [comment]
Unsure what could be causing this issue, fogtweaker can be safely removed from the pack without causing any issues tho, its only used to make it easier to see long distances in the nether.

I've brought this issue to the attention of the fogtweaker devs, hopefully I'll hear back from them soon.

**Comment by Warhand** [comment]
Closing this issue because in the latest version of the pack, fogtweaker has been replaced with Fog override.
